### ISSUE TITLE
Stayed on Joining Status

### ISSUE THREAD

**Issue by disk91** [cyberman54/ESP32-Paxcounter#149]
I'm experiencing some difficulties during Join process : multiple times the devices never moved from joining to joined status even if I see some regular Join communication on the LoRaWan network. I need to switch ON/OFF multiple times the device to get it working. 
I see about 1 join per minute but no success.

**Comment by cyberman54** [comment]
Join problems with LMIC usually depend on your LoRaWAN network provider settings, the configuration of the used gateway, or you have a too weak reception signal level for the OTAA handshake.

Since paxcounter relies on LMIC and LMIC is stable LoRaWAN stack, i close this issue here, because it assume it is not a paxcounter software related issue. If so, please state details on the here and reopen the issue.
