### ISSUE TITLE
Lora and senddata.cpp 

### ISSUE THREAD

**Issue by zoltan85000** [cyberman54/ESP32-Paxcounter#154]
Dear
I'm reading your beautiful work about PaxCounter based on Wifi/BLE scanner and ESP32.
I'm reading your source in order to anderstand alone the details. But after a couple of days; I have always some problems...

I'm a newby in Lora protocole. It's seem to me a node transmit data to a gateway.
No transmission between node or between gateway except if we uncomment in [paxcounter.conf](https://github.com/cyberman54/ESP32-Paxcounter/blob/master/src/paxcounter.conf):

> #define DISABLE_INVERT_IQ_ON_RX

My question where, for who, senddata.cpp send payload ? to a gateway, but I don't find specification of this gateway anywhere, in any configuration file ?

So in order to receive data from node (by default a paxcounter node); I must build a gateway to receive all data from the nodes, by using for example https://github.com/vpcola/ESP32SingleChannelGateway
It's true or I'm wrong ?

Sorry for may be a stupid question,
Best regards.
Philippe.

**Comment by cyberman54** [comment]
@zoltan85000 You need a LoRaWAN network, since paxcounter software does not support node-to-node communications via LoRa. That means, setup your own LoRaWAN gateway and connect it to either an own LoRaWAN server or to a public network like TheThingsNetwork. If you live in an area which has coverage by a commercial LoRaWAN network, you don't need own gateway. You can use the provider network (if you have access keys for it).
