### ISSUE TITLE
bad longitude

### ISSUE THREAD

**Issue by leatherbacks** [cyberman54/ESP32-Paxcounter#251]
I cannot seem to get a correct longitude out of either the "packed" or "Cayenne" decoders. All other data seems correct, see output from packed converter sent via TTN below:
{
  "altitude": 17,
  "hdop": 1.28,
  "latitude": 26.56843,
  "longitude": 2147.483647,
  "pax": 3,
  "sats": 7,
  "wifi": 3
}

I am using TTGO T-Beam (T22_V07 20180711 ) with the latest version of the software, and OLED display.

**Comment by cyberman54** [comment]
What is the expected longitude value, which country?

**Comment by leatherbacks** [comment]
Should be -80.xxx in the United States, Florida

**Comment by cyberman54** [comment]
really minus 80?

**Comment by leatherbacks** [comment]
Yes, should be around here: https://www.google.com/maps/place/26°12'08.1"N+80°09'31.7"W/@26.20225,-80.1609943

All other data appear to be correct. The error is only with the longitude.

**Comment by cyberman54** [comment]
Allright, i now see that i did not have in mind international users when developing the quick & dirty geo conversion parts, it sure is erraneous because does not handle negative values.

I tried a [small](https://github.com/cyberman54/ESP32-Paxcounter/commit/feb8b1111556542674bea1bf3369a962f36f5f65) fix and pushed it to master, could you please update and try again?

Probably there are some more modifications necessary. Maybe you can review the code and fix it?

**Comment by leatherbacks** [comment]
Yes. Your fix worked! I will see if there needs to be any other changes.

**Comment by cyberman54** [comment]
ok, i close this for now. Please re-open if you encounter further issues. Thanks!
