### ISSUE TITLE
BLE Scan not working

### ISSUE THREAD

**Issue by gesaleh** [cyberman54/ESP32-Paxcounter#272]
after activating blescan in 
**configmanager.cpp**
`  cfg.blescan = 1; `
**paxcounter.conf**
```
#define BLECOUNTER                      1       // activate if you want to use BLE count, at expense of memory

// BLE scan parameters
#define BLESCANTIME                     10       // [seconds] scan duration, 0 means infinite [default], see note below
#define BLESCANWINDOW                   80      // [milliseconds] scan window, see below, 3 .. 10240, default 80ms
#define BLESCANINTERVAL                 80      // [illiseconds] scan interval, see below, 3 .. 10240, default 80ms = 100% duty cycle
```
I still don't see BLE counting BLTH is displayed off on OLED
is there any other steps needed
using paltform.io did clean, build ,upload
Board TTGO V2.1

**Comment by cyberman54** [comment]
Try to send a remote command 0x0e 0x01 to enable bluetooth.

Go to TTN console, select your device, scroll down to downlink, set FPort to 2 and enter payload 0e 01. Then wait until the paxcounter received the command, it will then turn bluteooth on (if the feature was compiled in code).

You can also modify the default setting “blescan” in configmanager.cpp, then reflash and reboot.

**Note: If you modify setting in configmanager.cpp, it will not affect the runtime settings immediately, because settings are saved in NVRAM and reloaded at device startup.**  So you need to erase NVRAM settings with rcommand 09 02, or you increase the version number in platformio.ini. The device checks the version number during startup and if a newer version is detected, NVRAM settings are cleared.

Yes, this is weird, you’re welcome to make pull request with refactored configmanager.cpp code!
