### ISSUE TITLE
HELTECv2 + BME680 weird data

### ISSUE THREAD

**Issue by oscarmh** [cyberman54/ESP32-Paxcounter#423]
Hi, I´m testing the latest HeltecV2 for paxcounter but I´ve errors

0) Do a esptool.py erase_flash
1) git clone latest version 
2) activated BME680, recognized
3) TTN does not show correct data

![heltecboot](https://user-images.githubusercontent.com/17768352/64109886-e7cd2500-cd80-11e9-8df7-0c8326cef9d0.png)
![heltecdetail](https://user-images.githubusercontent.com/17768352/64109894-ed2a6f80-cd80-11e9-9f7a-b1c1c06fa91c.png)

Heltecv2.h hal file is the default one

#ifndef _HELTECV2_H
#define _HELTECV2_H

#include <stdint.h>

// Hardware related definitions for Heltec V2 LoRa-32 Board

#define HAS_BME 1 // Enable BME sensors in general
#define HAS_BME680 GPIO_NUM_4, GPIO_NUM_15 // SDA, SCL
#define BME680_ADDR BME680_I2C_ADDR_PRIMARY // connect SDIO of BME680 to GND 

#define HAS_LORA 1       // comment out if device shall not send data via LoRa
#define CFG_sx1276_radio 1

#define HAS_DISPLAY U8X8_SSD1306_128X64_NONAME_HW_I2C // OLED-Display on board
#define HAS_LED LED_BUILTIN                           // white LED on board
#define HAS_BUTTON KEY_BUILTIN                        // button "PROG" on board

//#define BAT_MEASURE_ADC ADC2_GPIO13_CHANNEL  // battery probe GPIO pin
//#define BAT_VOLTAGE_DIVIDER 4 // voltage divider 220k/100k on board
#define EXT_POWER_SW Vext // switches battery power, Vext control 0 = on / 1 = off
#define EXT_POWER_ON    0
//#define EXT_POWER_OFF   1

// Pins for I2C interface of OLED Display
#define MY_OLED_SDA SDA_OLED
#define MY_OLED_SCL SCL_OLED
#define MY_OLED_RST RST_OLED

// Pins for LORA chip SPI interface come from board file, we need some
// additional definitions for LMIC
#define LORA_IRQ DIO0
#define LORA_IO1 DIO1
#define LORA_IO2 DIO2
#define LORA_SCK SCK
#define LORA_MISO MISO
#define LORA_MOSI MOSI
#define LORA_RST RST_LoRa
#define LORA_CS SS

#endif

Any help ? Thanks in advance

**Comment by cyberman54** [comment]
I don't know which payload converter you're using to display data in console, but it sure is not that one from the paxcounter repository. So you may want to take a look to your console for solving this.

Meanwhile you posted several "issues" here, which in fact are support queries, not issues. Please stop misusing this issue tracker and post your questions on a [suitable forum] (https://www.thethingsnetwork.org/forum/t/wifi-ble-paxcounter-project-with-esp32-boards/13175), otherwise i would need to block you here.
