### ISSUE TITLE
Use button to switch SF modes

### ISSUE THREAD

**Issue by valentt** [cyberman54/ESP32-Paxcounter#502]
Currently paxcounter takes very long time to go from lower SF to higher SF. It would make sense to use button to switch spreafing factor.

For example when I'm testing range of Lora sensor it will always use SF12 but it takes almost 30 minutes to go from SF7 to SF12.

**Comment by cyberman54** [comment]
I won't implement this, since it would overrule settings of the (pre-compliant) LMIC stack.

If you really need a certain datarate / SF, set LORADRDEFAULT in paxcounter.conf accordingly.
I would suggest to keep ADR on (as it is by default) in such configurations to give the network control over the datarate.

Keep in mind that settings for the initial join procedure (OTAA) are still set by the network, not by the node. Thus, you cannot change SF parameters for OTAA.
