### ISSUE TITLE
Typical Range of Antenna?

### ISSUE THREAD

**Issue by jamessugrue** [cyberman54/ESP32-Paxcounter#603]
I'm curious, for a TTGO V2.1 board with the default antenna, what is the radius range for picking up WIFI devices? Is that range different if I just want to pick up BLE devices? And can that range be tweaked in the source code/configuration?

**Comment by cyberman54** [comment]
WIFI and BLE on ESP32 are both using the same RF path (2,4 GHz). So i assume the radio radius is the same, in terms of RF hardware. You can justify it by filtering devices using their RSSI value, see readme.md for further details.

But be aware that sniffing WIFI and BLE devices using the single radio of ESP32 produces different catching rates. Because signalisation on WIFI is using 13 channels, on BLE 3 channels. Thus, channel cycle frequency when sniffing BLE can be much higher, resulting in an increased propability to catch a signalisation packet.
