### ISSUE TITLE
No BATTERY status for T-Beam on paxcounter 2.0.x

### ISSUE THREAD

**Issue by PlumbumDN** [cyberman54/ESP32-Paxcounter#658]
After flashing paxcounter 2.0 on Sunday I experienced that my TTGO T-Beam has no battery status anymore.
You can see, that after flashing the cwa counter became active and battery voltage was missing.

I checked several things and measured the correct voltage on GPIO 35, thus I think the config and PIN mapping is correct.
Anyone else experiencing this?

![paxcounter_no_bat_status](https://user-images.githubusercontent.com/6172126/95293060-08648a00-0873-11eb-8f0a-900473a2b364.png)

**Comment by cyberman54** [comment]
What T-Beam version are you using? pre 1.0, 1.0 or 1.1.?

**Comment by PlumbumDN** [comment]
its a pre 1.0 (late 2018) T-Beam.

**Comment by cyberman54** [comment]
could you please try to change line122 in power.h from &sigmoidal to &linear and re-test?

**Comment by cyberman54** [comment]
And: which software version did you use before, that did show correct battery voltage values?

**Comment by PlumbumDN** [comment]
ok, change it to linear, but no values at all. 
![2020-10-07 10_46_26-Window](https://user-images.githubusercontent.com/6172126/95308603-6b155000-088a-11eb-8e12-ec97e8d2cce4.png)
Previous version on T-Beam was quite old... 1.8.2 if build logs are correct... but could be the result of not updating platformio.ini in the past.
Because of the big gap I reconfigured everything from scratch in 2.0.1x, cleared esp and did a fresh build

**Comment by cyberman54** [comment]
I will check this on a old T-Beam. Generally, battery monitoring was refactored and improved since 1.8.x, thus it is possible that a bug came in. The relevant code is in power.cpp

**Comment by PlumbumDN** [comment]
No hurry, just noticed the missing values ;-)

**Comment by cyberman54** [comment]
Turns out: it's not a bug, it's a feature.

With newer versions of paxcounter it is possible to control sending of device data more granular. See [description](https://github.com/cyberman54/ESP32-Paxcounter/blob/master/README.md#Sensors%20and%20Peripherals).
The default for battery values is now OFF. You can it turn it ON by once sending rcommand 0x16 0x01 to the device. The setting is stored in NVRAM then and thus will be persistant, until you change it again.
