### ISSUE TITLE
PaxCounter transmit power not changeable

### ISSUE THREAD

**Issue by paddlix** [cyberman54/ESP32-Paxcounter#860]
Hello,
I have a problem with my PaxCounter. The issue is the following: If I change the value for "txpower" in the paxcounter.conf, this has no effect on the transmit power of the PaxCounter. The changed value is stored on the device (picture, red circle - external readout of the configuration via TheThingsNetwork), but the device seems to ignore it and transmits with the default value txpower = 14 instead (picture, green circle - display of the PaxCounter). It does not matter which value is entered in paxcounter.conf. Neither 0, nor 255, nor any value in between has any effect.
Is there a software solution to this problem or is this a hardware malfunction?

The PaxCounter is a LILYGO TTGO ESP32 PaxCounter. It is set for use in the EU.

Thanks!
![IMG_0019](https://user-images.githubusercontent.com/100777763/156370022-9388e392-1ba4-4264-b49b-0c69f7491795.jpg)

**Comment by cyberman54** [comment]
1. Settings in paxcounter.conf define factory settings and only affect new builds. Settings are loaded during power up in NVRAM and thus persist, even if you flash a new build. Thus, if you changed factory settings, you need to manually clear NVRAM to avoid that previous values are loaded during startup. Use pio run -t erase to clear NVRAM manually.
2. Better option to tailor runtime settings is to use rcommands, see readme.md
3. TXpower is limited if ADR is switched in (which is the default), thus the radio driver will accept changes only by network, not by hand.

Open question is, why "25" is sent by the decive to the backup. This is probably a bug, because the administrative value is sent to the backend, while the actual the radio driver's value (limited by ADR) is displayed.

It's not a hardware issue.

Anyway, if you change TX power by hand, you should know your [local frequency regulations](https://www.thethingsnetwork.org/forum/t/tx-power-restriction/33365/5) limits.
