### ISSUE TITLE
Ratio measured WiFi devices vs. Bluetooth devices

### ISSUE THREAD

**Issue by ClemensGruber** [cyberman54/ESP32-Paxcounter#974]
We had set up one pax counter for a regular event (OpenHaus) at ZK/U Berlin to see how many people participate and how the distribution over time is: https://community.hiveeyes.org/t/openhaus-2023-05/4943#pax-counter-6 (German only but you can find a globe under every posting for (auto)translation). 

In a test setting before at home I observed more WiFi devices than Bluetooth, also: _Bluetooth is deactivated by default_ via `#define BLECOUNTER 0    // set to 0 if you do not want to start the BLE sniffer` in [paxcounter[_orig].conf](https://github.com/cyberman54/ESP32-Paxcounter/blob/master/src/paxcounter_orig.conf) so I assumed that the counted Wifi devices are "the standard" and relevant data and not Bluetooth. 

But the data from the OpenHaus event show now that Wifi devices over time are more or less stable with a baseline between 5 and 20 devices while the Bluetooth devices go up to 80 devices and representing in the run also the "felt" movement of people: 

![](https://community.hiveeyes.org/uploads/default/original/2X/3/3dbaf5dfb1263dfebe0e06f7a1649eb918772e97.png)

So my question to the crowd is: Did you observe similar ratios between WiFi and Bluetooth devices in Germany and is this "normal" or do I have a mismatch in the telemetry chain and swaped BLE and WiFi at some point, I have slightly adjusted the payload decoder (provided by TTN by choosing pax counter as device), but see no mistake on my side till now.

**Comment by cyberman54** [comment]
BLE values are usually up to ten times higher than Wifi values. Reasons are:
- BLE sniffing operates generally faster than Wifi, because BLE uses 3 signalling channels, while for Wifi 13 channels need to be scanned. ESP32 has ony a single radio, thus channels needs to be rotated, what means probabilty that a single device is sniffed at a certain time is 1/13 with wifi, while 1/3 with ble
- After introduction of corona tracing frameworks on smartphones, BLE sniffing rates increased.

I'm closing this, because it's not an issue. For further questions / discussions, please move to discussion tab.
