### ISSUE TITLE
TTNV3 has no Converter og Decoder page

### ISSUE THREAD

**Issue by JensBovbjergdk** [cyberman54/ESP32-Paxcounter#988]
TTNV3 has no Converter og Decoder page. Only Default uplink payload formatter.

This i a little confusing. Which one to use?

// Converter for device payload encoder "PLAIN"
// copy&paste to TTN Console -> Applications -> PayloadFormat -> Converter

and
// Decoder for device payload encoder "PLAIN"
// copy&paste to TTN Console -> Applications -> PayloadFormat -> Decoder

**Comment by cyberman54** [comment]
Look [here](https://www.thethingsindustries.com/docs/integrations/payload-formatters/) how to create payload formatters in TTNv3.

An example template for a paxcounter decoder is included in the src directory [here](https://github.com/cyberman54/ESP32-Paxcounter/tree/master/src/TTNv3).

If you don't want or need to edit the example template, it's not necessary to install a decoder manually, because there is paxcounter predefined decoder available from the TTN repository. When you registrate a device in TTN, 
- select option _Select the end device in the LoRaWAN Device Repository_,
- then brand _Open Source Community Project_, 
- then _ESP32-Paxcounter_. 

Going this way the paxcounter payload decoder will be automatically installed during device registration.
